### ISSUE TITLE
port 443 https doesnt work

### ISSUE THREAD

**Issue by dyanakiev** [codekitchen/dinghy-http-proxy#56]
I have this docker-compose

```
version: '3.8'

services:
  php:
    image: thecodingmachine/php:7.3-v4-apache
    environment:
        VIRTUAL_HOST: "x.test"
        APACHE_DOCUMENT_ROOT: public/
        APACHE_EXTENSIONS: "headers socache_shmcb ssl"
        HTTPS_METHOD: nohttp
        VIRTUAL_PROTO: https
        VIRTUAL_PORT: 443
    volumes:
      - /Users/dimitar/Projects/x:/var/www/html
      - /Users/dimitar/.dinghy/certs/x.test.crt:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - /Users/dimitar/.dinghy/certs/x.test.key:/etc/ssl/private/ssl-cert-snakeoil.key
```
      
Apperently the http-proxy doesnt like the upstream cert and i cant understand why..
Any ideas?
```

nginx.1    | 2021/02/13 00:02:45 [error] 721#721: *797 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 192.168.99.1, server: x.test, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.19.0.2:443/favicon.ico", host: "x.test", referrer: "https://x.test/?test"
```
